language: rust
sudo: false

matrix:
  include:
    - rust: stable
      script:
      - rustup component add rustfmt-preview --toolchain nightly
      - cargo +nightly fmt --all -- --check

    - rust: nightly
      script:
      - rustup component add rustfmt-preview
      - cargo fmt --all -- --check

  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose
