language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo build --verbose
