os:
  - linux
  - osx
  - windows

language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

install:
  - sudo apt-get install -y libasound2-dev libudev-dev pkg-config libx11-dev

script:
  - cargo build --verbose
