[package]
name = "atlas"
description = "🌈 3D game engine built using Rust"
version = "1.1.1"
authors = ["N U R O ™ <me@nuro.sh>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/nurodev/atlas"
exclude = ["example", "target"]
keywords = ["3D", "game engine", "gfx"]

[badges]
travis-ci = { repository = "nurodev/atlas", branch = "master" }

[lib]
name = "atlas"
path = "./src/lib.rs"

[[example]]
name = "sandbox"
path = "examples/sandbox/src/main.rs"

[dependencies]
env_logger = "0.6.2"
gfx-hal = "0.2.1"
log = "0.4.6"
nalgebra = "0.18.0"
quick-error = "1.2.2"
winit = "0.19.2"

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
version = "0.2"

[target.'cfg(target_os = "macos")'.dependencies.gfx-backend-metal]
version = "0.2"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.gfx-backend-vulkan]
version = "0.2"
