[package]
name = "atlas"
description = "🦀 3D game engine built using Rust"
version = "1.1.1"
authors = ["N U R O ™ <me@nuro.sh>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/nurodev/atlas"
exclude = ["example", "target"]
keywords = ["3D", "game engine", "gfx"]

[lib]
name = "atlas"
path = "./src/lib.rs"

[[example]]
name = "sandbox"
path = "examples/sandbox/src/main.rs"

[dependencies]
cgmath = "0.17.0"
env_logger = "0.6.2"
ezing = "0.2.1"
gfx-hal = "0.2.1"
ncollide3d = "0.19.2"
noise = "0.5.1"
log = "0.4.6"
quick-error = "1.2.2"
resource = "0.2.1"
rodio = "0.9.0"
specs = "0.15.0"
tobj = "0.1.7"
winit = "0.20.0-alpha2"

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
version = "0.2.1"

[target.'cfg(macos)'.dependencies.gfx-backend-metal]
version = "0.2.1"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.gfx-backend-vulkan]
version = "0.2.3"
