combine_control_expr = false
fn_single_line = true
format_macro_bodies = false
format_strings = true
hard_tabs = true
imports_indent = "Visual"
imports_layout = "Mixed"
indent_style = "Block"
match_block_trailing_comma = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
struct_lit_single_line = false
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
