[package]
name = "core"
version = "1.1.1"
authors = ["N U R O ™ <me@nuro.sh>"]
edition = "2018"

[dependencies]
env_logger = "0.6.2"
log = "0.4.6"
physics = { path = "../physics" }
renderer = { path = "../renderer" }
winit = "0.20.0-alpha2"
