[package]
name = "sandbox"
version = "1.1.1"
authors = ["N U R O ™ <me@nuro.sh>"]
edition = "2018"

[[bin]]
name = "sandbox"
path = "src/main.rs"

[dependencies]
atlas = { path = "../../atlas" }
env_logger = "0.6.2"
log = "0.4.6"
