[book]
title = "Atlas"
language = "en"
multilingual = false
src = "./src"
authors = ["N U R O ™ <me@nuro.sh>"]

[output.html]
git-repository-url = "https://github.com/nurodev/atlas"
additional-css = ["./custom.css"]

[build]
create-missing = true
build-dir = "public/"