[book]
title = "atlas"
src = "./src"
authors = ["N U R O ™ <me@nuro.sh>"]

[output.html]
git-repository-url = "https://github.com/nurodev/atlas"
additional-css = ["./custom.css"]

[build]
build-dir = "./public"
create-missing = true
