name: 📕 Book

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: cargo install mdbook --verbose
    - name: Build
      run: cd book && mdbook build
    - name: Deploy
      uses: actions/zeit-now@1.0.0
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
