name: 📕 Book

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.3.5'

    - name: Build
      working-directory: ./book
      run: |
        pwd
        ls
        mdbook build .

    - name: Deploy
      working-directory: ./book
      run: npx now --token=${{ secrets.ZEIT_TOKEN }} --prod
