name: 💡 Docs

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo doc --verbose --no-deps --features vulkan
    - name: Move
      run: mv -v target/doc/* docs/
    - name: Deploy
      run: cd docs/ && npx now --prod --token=${{ secrets.ZEIT_TOKEN }}
