name: 💡 Docs

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo doc --verbose --no-deps --features vulkan

    - name: Make Public Directory
      run: mkdir docs/public/

    - name: Move Build
      run: mv -v target/doc/* docs/public/

    - name: Deploy
      uses: amondnet/now-deployment@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
        now-args: '--prod ./docs'
