name: 💡 Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo doc --no-deps --features vulkan
    - name: Move
      run: mv -v target/doc/* docs/ && cd docs/
    - name: Deploy
      uses: actions/zeit-now@1.0.0
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
