name: 💡 Docs

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo doc --no-deps --features vulkan
    - name: Move
      run: mv -v target/doc/* docs/ && cd docs/
    - name: Deploy
      run: npx now --prod --token=${{ secrets.ZEIT_TOKEN }}
