name: Build | Engine

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        backend:
          - dx11
          - dx12
          - metal
          - vulkan
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
        toolchain:
          - stable
          - nightly
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --features ${{ matrix.backend }}
