name: 🚀 Engine

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        toolchain:
          - stable
          - beta
          - nightly
        include:
          - os: windows-latest
            backend:
              - dx11
              - dx12
          - os: macos-latest
            backend:
              - metal
          - os: ubuntu-latest
            backend:
              - vulkan
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --features ${{ matrix.backend }}
