name: Engine

on: [push]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        backend:
          - dx11
          - dx12
        toolchain:
          - stable
          - nightly
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --features ${{ matrix.backend }}
  mac:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --features metal
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --features vulkan
